export const {
    Button,
    Flex,
    Spinner,
    Text,
    ErrorBoundary,
    ColorInput,
    DropdownInput,
    KeybindInput,
    NumberInput,
    RadioInput,
    SearchInput,
    SliderInput,
    SwitchInput,
    TextInput,
    SettingItem,
    SettingGroup,
} = BdApi.Components;
