name: Tests

on:
  push:
    branches:
      - master
    paths:
      - dium/**
      - tests/**
      - package.json
  pull_request:
    branches:
      - master
    paths:
      - dium/**
      - tests/**
      - package.json

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test
